name: Run SDMs

on:
  workflow_dispatch:

jobs:
  run-models:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        batch: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true  # Use binary packages when available

      - name: Install system dependencies (macOS)
        run: |
          brew install gdal geos proj udunits

      - name: Install R packages
        run: |
          install.packages("pak")
          pak::pak(c(
            "dplyr",
            "stringr",
            "tibble",
            "sf",
            "sdmTMB",
            "pfmc-assessments/nwfscSurvey",
            "pfmc-assessments/indexwc"
          ))
        shell: Rscript {0}

      - name: Run SDMs with sdmTMB for Batch ${{ matrix.batch }}
        run: Rscript code/01_calculate_indices.R ${{ matrix.batch }}

      - name: Upload results for Batch ${{ matrix.batch }}
        uses: actions/upload-artifact@v4
        with:
          name: batch-${{ matrix.batch }}
          path: |
            output/
            diagnostics/
