name: R-run-models1

on:
  schedule:
    - cron: '0 0 2 1,4,7,10 *' # midnight UTC on the 2nd
  push:
    paths:
      - 'code/01_calculate_indices.R'

jobs:
  run-models:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false  # This prevents one failure from stopping all jobs
      matrix:
        batch: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2

      - name: Install packages
        run: Rscript -e "install.packages(c('remotes', 'dplyr', 'future', 'future.apply', 'sdmTMB', 'stringr', 'lubridate', 'tibble'))"

      - name: Install indexwc
        run: Rscript -e "remotes::install_github('pfmc-assessments/indexwc')"

      - name: Install nwfscSurvey
        run: Rscript -e "remotes::install_github('pfmc-assessments/nwfscSurvey')"

      - name: Run SDMs with sdmTMB for Batch ${{ matrix.batch }}
        run: Rscript code/01_calculate_indices.R ${{ matrix.batch }}

      - name: Upload results for Batch ${{ matrix.batch }}
        uses: actions/upload-artifact@v4
        with:
          name: batch-${{ matrix.batch }}
          path: |
            output/
            diagnostics/
